services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app                     # ✅ แก้ path mount ให้ถูกต้อง
      - static_volume:/app/static # ✅ สำหรับ static files ที่ collect ไว้
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000 # <--- จุดที่ 1

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mindvibe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  static_volume:
  postgres_data:
  media_volume:
