# Generated by Django 5.2.1 on 2025-05-13 14:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer_uploaded_image',
            field=models.ImageField(blank=True, help_text='ลูกค้าสามารถแนบรูปภาพที่เกี่ยวข้องกับคำสั่งซื้อนี้ (เช่น แจ้งปัญหา)', null=True, upload_to='customer_order_issues/'),
        ),
        migrations.AddField(
            model_name='cart',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='rental_status',
            field=models.CharField(blank=True, choices=[('pending_payment', 'รอการชำระเงิน'), ('processing', 'กำลังดำเนินการ'), ('shipped', 'จัดส่งแล้ว'), ('delivered', 'ลูกค้าได้รับแล้ว'), ('returned', 'ลูกค้าส่งคืนแล้ว'), ('completed', 'เสร็จสมบูรณ์'), ('cancelled', 'ยกเลิกแล้ว')], default='pending_payment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item_price_at_rental',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
