# Generated by Django 5.2.1 on 2025-05-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_cart_customer_uploaded_image_cart_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='rental_status',
            field=models.CharField(blank=True, choices=[('pending_payment', 'รอการชำระเงิน'), ('payment_confirmed', 'ยืนยันการชำระเงินแล้ว'), ('processing', 'กำลังเตรียมชุด'), ('shipped', 'จัดส่งแล้ว'), ('delivered', 'ลูกค้าได้รับแล้ว'), ('customer_returning', 'ลูกค้ากำลังส่งคืน'), ('returned_received', 'ร้านได้รับชุดคืนแล้ว'), ('completed', 'เสร็จสมบูรณ์'), ('issue_reported', 'ลูกค้าแจ้งปัญหา'), ('cancelled', 'ยกเลิกแล้ว')], default='pending_payment', max_length=25, null=True),
        ),
    ]
