# Generated by Django 5.2 on 2025-04-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_remove_outfit_image_url_outfit_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='price',
        ),
        migrations.AddField(
            model_name='outfit',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='image',
            field=models.ImageField(default='/static/outfits/default.jpg', upload_to='outfits/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outfit',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
