# Generated by Django 5.2 on 2025-04-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0003_remove_outfit_price_outfit_is_rented_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='outfits/'),
        ),
    ]
