# Generated by Django 5.2.1 on 2025-05-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0003_alter_cart_rental_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='return_shipment_image',
            field=models.ImageField(blank=True, null=True, upload_to='return_shipments/', verbose_name='รูปภาพหลักฐานการส่งคืน'),
        ),
        migrations.AddField(
            model_name='cart',
            name='return_tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขพัสดุส่งคืน'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='rental_status',
            field=models.CharField(blank=True, choices=[('pending_payment', 'รอการชำระเงิน'), ('payment_confirmed', 'ยืนยันการชำระเงินแล้ว'), ('processing', 'กำลังเตรียมชุด'), ('shipped', 'จัดส่งแล้ว'), ('delivered', 'ลูกค้าได้รับแล้ว'), ('customer_returning', 'ลูกค้าแจ้งส่งคืนแล้ว'), ('returned_received', 'ร้านได้รับชุดคืนแล้ว'), ('completed', 'เสร็จสมบูรณ์'), ('issue_reported', 'ลูกค้าแจ้งปัญหา'), ('cancelled', 'ยกเลิกแล้ว')], default='pending_payment', max_length=25, null=True),
        ),
    ]
