# Generated by Django 5.2.1 on 2025-05-13 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0004_cart_return_shipment_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อหมวดหมู่')),
                ('slug', models.SlugField(allow_unicode=True, help_text='ข้อความที่ใช้ใน URL (ภาษาอังกฤษหรือไทยก็ได้ เว้นวรรคจะถูกแทนที่ด้วยขีด)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบายหมวดหมู่ (ถ้ามี)')),
            ],
            options={
                'verbose_name': 'หมวดหมู่',
                'verbose_name_plural': 'หมวดหมู่ทั้งหมด',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='outfit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfits', to='outfits.category', verbose_name='หมวดหมู่'),
        ),
    ]
