# Generated by Django 5.2 on 2025-04-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0004_alter_outfit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outfit',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
