# Generated by Django 5.2 on 2025-04-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0006_outfit_rent_duration_alter_outfit_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='rent_duration',
            field=models.PositiveIntegerField(default=500),
            preserve_default=False,
        ),
    ]
