# Generated by Django 5.2 on 2025-04-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0008_remove_outfit_rent_duration_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='outfits/'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
