# Generated by Django 5.2 on 2025-04-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0009_alter_outfit_image_alter_outfit_price_delete_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
